url: https://y7kim.github.io
baseurl: ""

# Site settings
title: Tour de Bares
email: tourdebaresmvd@gmail.com
description: "Sitio web de la comunidad Tour de Bares. El mejor lugar para conocer gente."


# Team names, titles and social links
people:
- name: Andres Arbuet
  pic: 1
  position: Organizador
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Audrey Cicimbra
  pic: 2
  position: Organizadora
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Gonzalo Samarello
  pic: 3
  position: Organizador
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #
      
- name: Gala Stoyanova
  pic: 4
  position: Organizador
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #
      
- name: Luis Vidal
  pic: 5
  position: Pureba
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/tourdebaresmvd/
  - title: facebook
    url: https://www.facebook.com/tourdebaresmvd/
  - title: whatsapp
    url: https://chat.whatsapp.com/HduorolIGhVCZ4aVSW5TEC

# Build settings
markdown: kramdown
permalink: pretty
